name: conditions
on: [push] #trigger
jobs: 
  hello:
    runs-on: ubuntu-latest # Linux Os. We can have windows or MAC
    steps: # stages
      - name: pushing to feature branch
        if: github.ref == 'refs/heads/feature-**'
        run: echo "Welcome to feature branch - Github Actions"
      - name: pushing to main branch
        if: github.ref == 'refs/heads/main'
        run: echo "Welcome to main branch - Github Actions"