name: parallel-jobs
on: [push] #trigger
jobs:
  job-1: #these shoud be unique
    runs-on: ubuntu-latest # Linux Os. We can have windows or MAC
    steps: # stages
      - name: step-1
        run: echo "Hi, I am from job-1"

  job-2: #these shoud be unique
    runs-on: ubuntu-latest # Linux Os. We can have windows or MAC
    steps: # stages
      - name: step-2
        run: echo "Hi, I am from job-2"

  job-3: #these shoud be unique
    runs-on: ubuntu-latest # Linux Os. We can have windows or MAC
    steps: # stages
      - name: step-3
        run: echo "Hi, I am from job-3"